public class ArithmaticCalculations {
    public integer addition(integer x, integer y){
        integer z = x + y;
        return z;
    }
    public integer subtraction(integer x, integer y){
        integer z = x - y;
        return z;
    }  
    public integer  multiplication(integer w, integer x, integer y){
        integer z = w * x * y;
        return z;
    }
    public string concatStrings(string a, string b){
        string z = a + ' & ' + b;
        return z;
    }    
}