public class CheckDatatypes {
    public void methodBoolean(){
        Boolean checkBoolean= true;
        System.debug(checkBoolean);
    }


    public void methodInteger(){
        integer varfirst = 1;
        System.debug(varfirst);
        Integer varsecond = 2;
        system.debug(varsecond);
    }
    
    public void stringMethod(){
        string varName = 'Name';
        string varName2 = 'Seyma';

        system.debug(varName);
        system.debug(varName2);
    }
    
    public void checkId(){
        id myId = '001Dn00000DKmx1IAD';
        system.debug(myId);

    }
    public void methodDouble(){
        Decimal varfirst= 1.23;
        system.debug(varfirst);
        Double varsecond= 209.764;
        system.debug(varsecond);
    }
}