public  class SalesforceDeveloper {
    public void myFirstCode() {
        system.debug('Istanbul');
        system.debug('The Notebook');
        system.debug('Autumn');

    }
    public void myFavorites(){
        integer favNum = 7;
        system.debug(favNum);
        string myCity ='Cincinnati';
        system.debug(myCity);
       
        system.debug('Favori numaram -> ' + favNum + ' ve yasadigim sehir ->  ' + myCity );

    }
}