public class AssetTriggerHandler {
    public static integer countTriggerRan=0;
    public static integer numberOFRecordsInserted=0;




    //dml if you wanna check paste it to any anonymous apex 
    // account acc =[select id, name from account order by LastModifiedDate desc limit 1];
    // list<assert> la = new list<asset>();
    // for(integer i=0; i<210; i++){
    //     asset a= new asset();
    //     a.name='aa'+i;
    //     a.accountid =acc.id;
    //     la.add(a);
    // }
    // insert la;
}