Dog d1 =new Dog();
system.debug(d1);
system.debug('--------------------------------------------------------');
Dog d2 = new Dog('Bruno', 'Black', 6);
system.debug(d2);
system.debug('--------------------------------------------------------');
Dog d3 =new Dog();
system.debug(d3);
system.debug('--------------------------------------------------------');
Dog d4 = new Dog('Mojo', 'Brown', 2);
system.debug(d4);






