string city;
system.debug(city);

string country= '';
system.debug(country);

string region = 'America';
system.debug('Amerika');
system.debug(region);

integer sayi1 =50;
System.debug(sayi1);

integer sayi2 = sayi1/2;
System.debug(sayi2);

Boolean isActive =true;
System.debug(isActive);

Boolean cond1 =7>3;
system.debug('con1 =' + cond1);

Boolean cond2 =11>35;
system,debug('cond2 = ' + cond2);

