setDemo.citySet();

SetDemo.randomIntegerSet();

set<boolean> bs = new set<boolean>(); //Only one true, false,and null will be output
bs.add(true);
bs.add(false);
bs.add(null);
bs.add(true);
bs.add(false);
bs.add(null);
system.debug(bs);

SetDemo.setFromList();

set<integer> ns;
ns.add(10); //will this work? no work

list<integer>l;
boolean check =l.isEmpty();

string s = '';
s.toUpperCase();

integer i =0;
system.debug(i+10);

SetDemo.citySet();

setDemo.upperCAseSet();

