string firstVariable ='This is a first variable';
system.debug(firstVariable);

firstVariable='updating first variable';
System.debug('After update firstvariable ==> ' + firstVariable);

String secondVariable = 'This s a second variable';
System.debug('Secondvariable ====> ' + secondVariable);

system.debug(1);
system.debug(2);
system.debug(3);
system.debug(4);
system.debug(5);
system.debug(6);


