Greetings g1= new Greetings();
g1.language ='Hindi';
string g1Greet = g1.greetingHello2();
system.debug(g1Greet);

Greetings g2 = new Greetings();
g2.language='Turkish';
string g2Greet = g2.greetingHello2();
system.debug(g2Greet);

Greetings g3 = new Greetings();
g3.language='Russian';
string g3Greet = g3.greetingHello2();
system.debug(g3Greet);

Greetings g4 = new Greetings();
g4.language = 'Eng';
System.debug(g4.greetingHello2());

